revoke delete on table "public"."employee_second" from "anon";

revoke insert on table "public"."employee_second" from "anon";

revoke references on table "public"."employee_second" from "anon";

revoke select on table "public"."employee_second" from "anon";

revoke trigger on table "public"."employee_second" from "anon";

revoke truncate on table "public"."employee_second" from "anon";

revoke update on table "public"."employee_second" from "anon";

revoke delete on table "public"."employee_second" from "authenticated";

revoke insert on table "public"."employee_second" from "authenticated";

revoke references on table "public"."employee_second" from "authenticated";

revoke select on table "public"."employee_second" from "authenticated";

revoke trigger on table "public"."employee_second" from "authenticated";

revoke truncate on table "public"."employee_second" from "authenticated";

revoke update on table "public"."employee_second" from "authenticated";

revoke delete on table "public"."employee_second" from "service_role";

revoke insert on table "public"."employee_second" from "service_role";

revoke references on table "public"."employee_second" from "service_role";

revoke select on table "public"."employee_second" from "service_role";

revoke trigger on table "public"."employee_second" from "service_role";

revoke truncate on table "public"."employee_second" from "service_role";

revoke update on table "public"."employee_second" from "service_role";

revoke delete on table "public"."student" from "anon";

revoke insert on table "public"."student" from "anon";

revoke references on table "public"."student" from "anon";

revoke select on table "public"."student" from "anon";

revoke trigger on table "public"."student" from "anon";

revoke truncate on table "public"."student" from "anon";

revoke update on table "public"."student" from "anon";

revoke delete on table "public"."student" from "authenticated";

revoke insert on table "public"."student" from "authenticated";

revoke references on table "public"."student" from "authenticated";

revoke select on table "public"."student" from "authenticated";

revoke trigger on table "public"."student" from "authenticated";

revoke truncate on table "public"."student" from "authenticated";

revoke update on table "public"."student" from "authenticated";

revoke delete on table "public"."student" from "service_role";

revoke insert on table "public"."student" from "service_role";

revoke references on table "public"."student" from "service_role";

revoke select on table "public"."student" from "service_role";

revoke trigger on table "public"."student" from "service_role";

revoke truncate on table "public"."student" from "service_role";

revoke update on table "public"."student" from "service_role";

alter table "public"."employee_second" drop constraint "employee_second_pkey";

alter table "public"."student" drop constraint "student_pkey";

drop index if exists "public"."employee_second_pkey";

drop index if exists "public"."student_pkey";

drop table "public"."employee_second";

drop table "public"."student";

create table "public"."dsignation" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."dsignation" enable row level security;

CREATE UNIQUE INDEX dsignation_pkey ON public.dsignation USING btree (id);

alter table "public"."dsignation" add constraint "dsignation_pkey" PRIMARY KEY using index "dsignation_pkey";

grant delete on table "public"."dsignation" to "anon";

grant insert on table "public"."dsignation" to "anon";

grant references on table "public"."dsignation" to "anon";

grant select on table "public"."dsignation" to "anon";

grant trigger on table "public"."dsignation" to "anon";

grant truncate on table "public"."dsignation" to "anon";

grant update on table "public"."dsignation" to "anon";

grant delete on table "public"."dsignation" to "authenticated";

grant insert on table "public"."dsignation" to "authenticated";

grant references on table "public"."dsignation" to "authenticated";

grant select on table "public"."dsignation" to "authenticated";

grant trigger on table "public"."dsignation" to "authenticated";

grant truncate on table "public"."dsignation" to "authenticated";

grant update on table "public"."dsignation" to "authenticated";

grant delete on table "public"."dsignation" to "service_role";

grant insert on table "public"."dsignation" to "service_role";

grant references on table "public"."dsignation" to "service_role";

grant select on table "public"."dsignation" to "service_role";

grant trigger on table "public"."dsignation" to "service_role";

grant truncate on table "public"."dsignation" to "service_role";

grant update on table "public"."dsignation" to "service_role";


